/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "pb/boardcomms.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CoralToATMega, CoralToATMega, AUTO)


PB_BIND(ATMegaToCoral, ATMegaToCoral, AUTO)





